#!/bin/bash

set -eEu
set -o pipefail

###########################################################
#### BOOTSTRAP THE ENVIRONMENT         ####################
###########################################################

. sdlc/functions.sh

main() {
    setup_python_path
    install_precommit
    add_upstream
    fetch_upstream
}

setup_python_path() {
    PYTHON_PATH="$(python -c "import site; print(site.USER_BASE)")"
    readonly PYTHON_PATH

    if ! grep "${PYTHON_PATH}/bin" <(printenv PATH) &>/dev/null; then
        run export PATH="${PATH}:${PYTHON_PATH}/bin"
    fi
}

install_precommit() {
    if ! command -v pre-commit &>/dev/null; then
        pip3 install --user -Iv --compile --no-cache-dir pre-commit
    fi
}

add_upstream() {
    upstream_uri=''
    if git remote show upstream | grep "${upstream_uri}" &>/dev/null; then
        info 'Upstream git repo is correct.'
    else
        git remote rm upstream || :
        git remote add upstream "${upstream_uri}"
    fi
}

fetch_upstream() {
    run git fetch --all
}
