#!/bin/bash
set -eEu
set -o pipefail

#######################################################
#### BUILD THE IMAGE ##################################
#######################################################

cat >sdlc/vars <<EOF
export BUILD_DATE=$(date +%Y%m%dT%H%M)
export VCS_REF=$(git rev-parse --short HEAD)
export TAG=$(date +%Y%m%d.%H%M)
EOF

. sdlc/vars

sudo docker-compose build
