#!/bin/bash

set -eEu
set -o pipefail

#########################################################
##### PUBLISH THE IMAGES TO DOCKER HUB        ###########
#########################################################

. sdlc/vars
. sdlc/functions.sh

sudo docker login -u "${user}" -p "${pass}"
sudo docker-compose push "${image}"
sudo docker logout
