#!/usr/bin/env bash

set -eEu
set -o pipefail

#
# sdlc/setup <image-name>
#

if [[ "$#" -ne 1 ]]; then
  echo "[ERROR] Must pass image name as first argument" >&2
fi

# overwrite the old image tags with the project name
sed -i.bak "s|spiffybox|$1|g" docker-compose.yaml

# remove old files
rm docker-compose.yaml.bak
