let g:gitgutter_enabled = 1
set background=dark
set number

set backspace=indent,eol,start
set mouse=a
set tabstop=4
syntax on
resize 15

set backupdir=.backup/,~/.backup/,/tmp//
set directory=.swp/,~/.swp,/tmp//
set undodir=.undo/,~/.undo/,/tmp//
