autocmd vimenter * NERDTree
let g:gitgutter_enabled = 1
set background=dark

if has('termguicolors')
	set termguicolors " 24-bit terminal
else
	let g:synthwave_termcolors=256 " 256 color mode
endif

set backspace=indent,eol,start
set mouse=a
set tabstop=4
syntax on
botright terminal
resize 15

set backupdir=.backup/,~/.backup/,/tmp//
set directory=.swp/,~/.swp,/tmp//
set undodir=.undo/,~/.undo/,/tmp//
