" basics
set encoding=utf-8
set number

" case
set ignorecase
set smartcase
set incsearch
set lazyredraw
set magic
set showmatch

set backspace=indent,eol,start
set mouse=a
let g:gitgutter_enabled = 1

" tabs + spaces
set expandtab
set smarttab
set shiftwidth=4
set tabstop=4

syntax enable
resize 40

" ux stuff
set showcmd
set showmode

" completions
set wildmenu
set wildmode=list:longest
set completeopt=menu,menuone,longest
set pumheight=15

" backupconfigs
set backupdir=.backup/,~/.backup/,/tmp//
set directory=.swp/,~/.swp,/tmp//
set undodir=.undo/,~/.undo/,/tmp//

" Disable scrollbars
set guioptions-=r
set guioptions-=R
set guioptions-=l
set guioptions-=L

" colors scheme
set background=dark

" more
set ruler
set cmdheight=1
set hid
set hlsearch
set foldcolumn=1

" lines
set lbr
set tw=500
set ai
set si
set wrap

let g:jedi#auto_initialization = 0
let g:jedi#auto_vim_configuration = 0

call plug#begin()
" The default plugin directory will be as follows:
"   - Vim (Linux/macOS): '~/.vim/plugged'
"   - Vim (Windows): '~/vimfiles/plugged'
"   - Neovim (Linux/macOS/Windows): stdpath('data') . '/plugged'
" You can specify a custom plugin directory by passing it as the argument
"   - e.g. `call plug#begin('~/.vim/plugged')`
"   - Avoid using standard Vim directory names like 'plugin'

" Make sure you use single quotes

" Shorthand notation; fetches https://github.com/junegunn/vim-easy-align
Plug 'junegunn/vim-easy-align'

" Any valid git URL is allowed
Plug 'https://github.com/junegunn/vim-github-dashboard.git'

" Multiple Plug commands can be written in a single line using | separators
Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'

" On-demand loading
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'tpope/vim-fireplace', { 'for': 'clojure' }

" Using a non-default branch
Plug 'rdnetto/YCM-Generator', { 'branch': 'stable' }

" Using a tagged release; wildcard allowed (requires git 1.9.2 or above)
Plug 'fatih/vim-go', { 'tag': '*' }

" vim-surround
Plug 'tpope/vim-surround'
Plug 'tpope/vim-fugitive'

" Plugin options
Plug 'nsf/gocode', { 'tag': 'v.20150303', 'rtp': 'vim' }

" Plugin outside ~/.vim/plugged with post-update hook
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }

" Unmanaged plugin (manually installed and updated)
Plug '~/my-prototype-plugin'

" Initialize plugin system
call plug#end()


" autocmd
autocmd VimEnter * NERDTree





